DB_USERNAME = 'korea'
DB_PASSWORD = 'korea1234'
DB_HOST = 'ai-server-01'
DB_PORT = 3306
DB_NAME = 't1'

SQLALCHEMY_DATABASE_URI = f'mysql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
SQLALCHEMY_TRACK_MODIFICATIONS = False